// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrfRidersBot.Persistence;
using UrfRidersBot.Persistence.Common;

namespace UrfRidersBot.Persistence.Migrations
{
    [DbContext(typeof(UrfRidersDbContext))]
    [Migration("20210302153028_AddColorRoles")]
    partial class AddColorRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("UrfRidersBot.Core.Entities.AutoVoiceChannel", b =>
                {
                    b.Property<decimal>("VoiceChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("VoiceChannelId", "GuildId");

                    b.ToTable("AutoVoiceChannels");
                });

            modelBuilder.Entity("UrfRidersBot.Core.Entities.GuildSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AdminRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("CustomPrefix")
                        .HasColumnType("text");

                    b.Property<decimal?>("MemberRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModeratorRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("UrfRidersBot.Persistence.DTOs.ColorRoleDTO", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId", "RoleId", "UserId");

                    b.HasIndex("GuildId", "RoleId")
                        .IsUnique();

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("ColorRoles");
                });

            modelBuilder.Entity("UrfRidersBot.Persistence.DTOs.ReactionRoleDTO", b =>
                {
                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Emoji")
                        .HasColumnType("text");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("MessageId", "Emoji", "RoleId");

                    b.HasIndex("MessageId", "Emoji")
                        .IsUnique();

                    b.HasIndex("MessageId", "RoleId")
                        .IsUnique();

                    b.ToTable("ReactionRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
