// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrfRidersBot.Persistence;

namespace UrfRidersBot.Persistence.Migrations
{
    [DbContext(typeof(UrfRidersDbContext))]
    partial class UrfRidersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("UrfRidersBot.Core.Entities.AutoVoiceChannel", b =>
                {
                    b.Property<decimal>("VoiceChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("VoiceChannelId", "GuildId");

                    b.ToTable("AutoVoiceChannels");
                });

            modelBuilder.Entity("UrfRidersBot.Core.Entities.GuildSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AdminRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("CustomPrefix")
                        .HasColumnType("text");

                    b.Property<decimal?>("MemberRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("ModeratorRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("UrfRidersBot.Core.Entities.ReactionHandlerInfo", b =>
                {
                    b.Property<decimal>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("ActiveReactionHandlers");
                });

            modelBuilder.Entity("UrfRidersBot.Core.Entities.ReactionTrackerData", b =>
                {
                    b.Property<decimal>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("MessageId");

                    b.ToTable("ReactionTrackerData");
                });
#pragma warning restore 612, 618
        }
    }
}
